# Generated by Django 5.0.6 on 2026-06-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RandomForestClassifier', max_length=80)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1', models.FloatField()),
                ('confusion_matrix', models.JSONField()),
                ('classes', models.JSONField()),
                ('feature_importances', models.JSONField()),
                ('n_samples', models.IntegerField()),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
    ]
