# Generated by Django 5.0.6 on 2026-06-23 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('imc_clasificacion', models.CharField(choices=[('bajo_peso', 'Bajo peso'), ('normal', 'Normal'), ('sobrepeso', 'Sobrepeso'), ('obesidad', 'Obesidad')], max_length=20)),
                ('presion_sistolica', models.IntegerField()),
                ('presion_diastolica', models.IntegerField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('glucosa', models.FloatField()),
                ('colesterol', models.FloatField()),
                ('saturacion_oxigeno', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(blank=True, max_length=30)),
                ('diagnostico_preliminar', models.CharField(blank=True, max_length=120)),
                ('riesgo_enfermedad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=10)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('rows_extracted', models.IntegerField(default=0)),
                ('rows_after_transform', models.IntegerField(default=0)),
                ('rows_loaded', models.IntegerField(default=0)),
                ('duplicates_removed', models.IntegerField(default=0)),
                ('nulls_imputed', models.IntegerField(default=0)),
                ('outliers_fixed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('partial', 'Parcial')], default='ok', max_length=10)),
                ('log', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
